import {createClient} from "@/lib/supabase/server";
import {revalidatePath} from "next/cache";
import {Plus,Search,Trash2} from "lucide-react";
import {PageHeader,InitialAvatar} from "@/components/ModuleUI";
const statuses=["novo","triagem","entrevista","aprovado","reprovado","desistiu","contratado"];
const labels:any={novo:"Novo",triagem:"Triagem",entrevista:"Entrevistas",aprovado:"Finalistas",reprovado:"Reprovado",desistiu:"Desistiu",contratado:"Contratados"};
export default async function Page(){
 async function vincular(f:FormData){"use server";const s=await createClient();await s.from("candidaturas").insert({candidato_id:String(f.get("candidato_id")),vaga_id:String(f.get("vaga_id")),origem:String(f.get("origem")||"")||null});revalidatePath("/candidaturas")}
 async function status(f:FormData){"use server";const s=await createClient();await s.from("candidaturas").update({status:String(f.get("status"))}).eq("id",String(f.get("id")));revalidatePath("/candidaturas")}
 async function excluir(f:FormData){"use server";const s=await createClient();await s.from("candidaturas").delete().eq("id",String(f.get("id")));revalidatePath("/candidaturas")}
 const s=await createClient();const[{data:rows},{data:candidatos},{data:vagas}]=await Promise.all([s.from("candidaturas").select("*,candidatos(nome,email,cargo),vagas(cargo,empresas(nome))").order("inscrito_em",{ascending:false}),s.from("candidatos").select("id,nome").order("nome"),s.from("vagas").select("id,cargo,empresas(nome)").in("status",["rascunho","em_andamento"]).order("cargo")]);const list:any[]=rows||[];
 return <section className="module-page"><PageHeader title="Processos Seletivos" description="Acompanhe os candidatos em cada etapa do processo seletivo." action={<details className="action-popover"><summary><Plus size={15}/> Adicionar candidato</summary><form action={vincular} className="popover-form"><select name="candidato_id" required defaultValue=""><option value="" disabled>Candidato</option>{(candidatos||[]).map((x:any)=><option key={x.id} value={x.id}>{x.nome}</option>)}</select><select name="vaga_id" required defaultValue=""><option value="" disabled>Vaga</option>{(vagas||[]).map((x:any)=><option key={x.id} value={x.id}>{x.cargo} — {x.empresas?.nome||""}</option>)}</select><input name="origem" placeholder="Origem"/><button className="primary-button">Adicionar</button></form></details>}/>
 <form className="module-panel process-filters"><select><option>Todas as vagas</option></select><select><option>Todos os responsáveis</option></select><select><option>Todos os status</option></select><select><option>Todos os períodos</option></select><label className="searchbox"><Search size={14}/><input placeholder="Buscar candidato..."/></label><button className="primary-button">Filtrar</button></form>
 <div className="module-panel kanban-panel"><div className="kanban-grid">{["novo","triagem","entrevista","aprovado","contratado"].map((st)=><div className={`kanban-column col-${st}`} key={st}><div className="kanban-title"><b>{labels[st]}</b><span>{list.filter(x=>x.status===st).length}</span></div>{list.filter(x=>x.status===st).map((r:any,i:number)=><article className="kanban-card process-card" key={r.id}><InitialAvatar name={r.candidatos?.nome||"AP"} index={i}/><div><b>{r.candidatos?.nome||"—"}</b><small>{r.vagas?.cargo||"—"} · {r.vagas?.empresas?.nome||"—"}</small></div><form action={status}><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue={r.status}>{statuses.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select><button>→</button></form></article>)}</div>)}</div></div>
 <div className="module-panel"><div className="panel-heading"><b>Candidaturas</b><span>{list.length} registro(s)</span></div><div className="table-wrap"><table className="module-table"><thead><tr><th>Candidato</th><th>Vaga</th><th>Empresa</th><th>Origem</th><th>Etapa</th><th>Ações</th></tr></thead><tbody>{list.map((r:any)=><tr key={r.id}><td><b>{r.candidatos?.nome||"—"}</b></td><td>{r.vagas?.cargo||"—"}</td><td>{r.vagas?.empresas?.nome||"—"}</td><td>{r.origem||"—"}</td><td><form action={status} className="inline-form"><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue={r.status}>{statuses.map(x=><option key={x} value={x}>{labels[x]||x}</option>)}</select><button className="small-button">Salvar</button></form></td><td><form action={excluir}><input type="hidden" name="id" value={r.id}/><button className="icon-button" title="Excluir"><Trash2 size={14}/></button></form></td></tr>)}</tbody></table></div></div></section>
}