import {createClient} from '@/lib/supabase/server';
import {revalidatePath} from 'next/cache';
import {ActionModal} from '@/components/ActionModal';
const comps=['Comunicação','Organização','Proatividade','Trabalho em equipe','Conhecimento técnico','Liderança'];
const decisionLabel:Record<string,string>={aprovar:'Aprovado',reprovar:'Reprovado',pendente:'Pendente'};
export default async function Page(){
 async function salvar(f:FormData){'use server';const s=await createClient();const{data:{user}}=await s.auth.getUser();const decisao=String(f.get('decisao')||'pendente');const candidatura_id=String(f.get('candidatura_id'));await s.from('avaliacoes').insert({candidatura_id,operador_id:user?.id||null,nota_tecnica:Number(f.get('nota_tecnica')),competencias:f.getAll('competencias').map(String),parecer:String(f.get('parecer')||'')||null,decisao});if(decisao!=='pendente')await s.from('candidaturas').update({status:decisao==='aprovar'?'aprovado':'reprovado'}).eq('id',candidatura_id);revalidatePath('/avaliacoes');revalidatePath('/candidaturas')}
 async function editar(f:FormData){'use server';const s=await createClient();const decisao=String(f.get('decisao')||'pendente');const candidatura_id=String(f.get('candidatura_id'));await s.from('avaliacoes').update({nota_tecnica:Number(f.get('nota_tecnica')),competencias:f.getAll('competencias').map(String),parecer:String(f.get('parecer')||'')||null,decisao}).eq('id',String(f.get('id')));if(decisao!=='pendente')await s.from('candidaturas').update({status:decisao==='aprovar'?'aprovado':'reprovado'}).eq('id',candidatura_id);revalidatePath('/avaliacoes');revalidatePath('/candidaturas')}
 const s=await createClient();const[{data:candidaturas},{data:rows}]=await Promise.all([s.from('candidaturas').select('id,status,candidatos(nome),vagas(cargo,empresas(nome))').not('status','in','("contratado","desistiu")'),s.from('avaliacoes').select('*,candidaturas(candidatos(nome),vagas(cargo)),usuarios(nome)').order('created_at',{ascending:false})]);
 return <section className="module-page"><h1 className="page-title">Avaliação de Candidatos</h1><p className="muted">Registre critérios técnicos, competências e parecer por processo.</p>
 <div className="card form-card"><form action={salvar} className="evaluation-form"><div className="field-group"><label>Candidato / vaga</label><select name="candidatura_id" required defaultValue=""><option value="" disabled>Selecione</option>{(candidaturas||[]).map((x:any)=><option key={x.id} value={x.id}>{x.candidatos?.nome} — {x.vagas?.cargo}</option>)}</select></div><div className="field-group"><label>Nota técnica</label><select name="nota_tecnica" required defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{'★'.repeat(n)} ({n})</option>)}</select></div><div className="competencias"><b>Competências</b><div className="check-grid">{comps.map(x=><label key={x}><input type="checkbox" name="competencias" value={x}/> {x}</label>)}</div></div><div className="field-group full"><label>Parecer final</label><textarea name="parecer" rows={4}/></div><div className="decision-row"><button className="button" name="decisao" value="aprovar">Aprovar</button><button className="danger-button" name="decisao" value="reprovar">Reprovar</button><button className="small-button" name="decisao" value="pendente">Salvar parecer</button></div></form></div>
 <div className="card table-card"><h2 className="section-title">Histórico</h2><div className="table-wrap"><table><thead><tr><th>Candidato</th><th>Vaga</th><th>Nota</th><th>Operador</th><th>Decisão</th><th>Ações</th></tr></thead><tbody>{(rows||[]).map((r:any)=><tr key={r.id}><td>{r.candidaturas?.candidatos?.nome||'—'}</td><td>{r.candidaturas?.vagas?.cargo||'—'}</td><td>{'★'.repeat(r.nota_tecnica)}</td><td>{r.usuarios?.nome||'—'}</td><td><span className={'badge '+(r.decisao==='aprovar'?'green':r.decisao==='reprovar'?'red':'blue')}>{decisionLabel[r.decisao]||r.decisao}</span></td><td><ActionModal kind="edit" title={r.candidaturas?.candidatos?.nome||'Avaliação'}><form action={editar}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="candidatura_id" value={r.candidatura_id}/><label>Nota técnica<select name="nota_tecnica" defaultValue={String(r.nota_tecnica)}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{'★'.repeat(n)} ({n})</option>)}</select></label><fieldset className="wide"><legend>Competências</legend>{comps.map(x=><label className="company-check" key={x}><input type="checkbox" name="competencias" value={x} defaultChecked={(r.competencias||[]).includes(x)}/>{x}</label>)}</fieldset><label className="wide">Parecer<textarea name="parecer" rows={4} defaultValue={r.parecer||''}/></label><label>Decisão<select name="decisao" defaultValue={r.decisao}><option value="pendente">Pendente</option><option value="aprovar">Aprovar</option><option value="reprovar">Reprovar</option></select></label><button className="primary-button">Salvar alterações</button></form></ActionModal></td></tr>)}</tbody></table></div></div></section>
}