import {createClient} from '@/lib/supabase/server';
import {revalidatePath} from 'next/cache';
import {EditModal,DeleteButton} from '@/components/RecordActions';
import {label,badgeClass} from '@/lib/format';

export default async function Page(){
  async function criar(f:FormData){'use server';const s=await createClient();await s.from('financeiro').insert({vaga_id:String(f.get('vaga_id')),valor:Number(f.get('valor')||0),percentual:Number(f.get('percentual')||0),data_vencimento:String(f.get('data_vencimento')||'')||null,observacoes:String(f.get('observacoes')||'')||null});revalidatePath('/financeiro')}
  async function editar(f:FormData){'use server';const s=await createClient();const pago=f.get('pago')==='on';await s.from('financeiro').update({valor:Number(f.get('valor')||0),percentual:Number(f.get('percentual')||0),status:String(f.get('status')||'pendente'),pago,data_vencimento:String(f.get('data_vencimento')||'')||null,data_pagamento:String(f.get('data_pagamento')||'')||null,nota_emitida:f.get('nota_emitida')==='on',numero_nota:String(f.get('numero_nota')||'')||null,observacoes:String(f.get('observacoes')||'')||null}).eq('id',String(f.get('id')));revalidatePath('/financeiro')}
  async function excluir(f:FormData){'use server';const s=await createClient();await s.from('financeiro').delete().eq('id',String(f.get('id')));revalidatePath('/financeiro')}
  async function baixar(f:FormData){'use server';const s=await createClient();const pago=f.get('pago')==='true';await s.from('financeiro').update({pago,status:pago?'pago':'pendente',data_pagamento:pago?new Date().toISOString().slice(0,10):null}).eq('id',String(f.get('id')));revalidatePath('/financeiro')}
  const s=await createClient();
  const[{data:rows},{data:vagas}]=await Promise.all([s.from('financeiro').select('*,vagas(cargo,empresas(nome))').order('created_at',{ascending:false}),s.from('vagas').select('id,cargo,empresas(nome)').order('created_at',{ascending:false})]);
  const data=rows||[];const total=data.reduce((a:any,r:any)=>a+Number(r.valor||0),0);const pend=data.filter((r:any)=>!r.pago&&r.status!=='cancelado').reduce((a:any,r:any)=>a+Number(r.valor||0),0);
  return <section><h1 className="page-title">Financeiro</h1><p className="muted">Controle financeiro dos processos de recrutamento.</p>
    <div className="grid summary-grid"><div className="card"><div className="muted">Valor total</div><div className="kpi-value">{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div></div><div className="card"><div className="muted">Pendente</div><div className="kpi-value">{pend.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div></div></div>
    <details className="card form-card vacancy-details"><summary>+ Novo lançamento</summary><form action={criar} className="quick-form"><div className="field-group"><label>Vaga</label><select name="vaga_id" required defaultValue=""><option value="" disabled>Selecione</option>{(vagas||[]).map((x:any)=><option key={x.id} value={x.id}>{x.cargo} — {x.empresas?.nome||''}</option>)}</select></div><div className="field-group"><label>Valor</label><input name="valor" type="number" step="0.01" min="0" required/></div><div className="field-group"><label>Comissão %</label><input name="percentual" type="number" step="0.01" min="0" max="100" defaultValue="0"/></div><div className="field-group"><label>Vencimento</label><input name="data_vencimento" type="date"/></div><div className="field-group"><label>Observação</label><input name="observacoes"/></div><button className="button">Lançar</button></form></details>
    <div className="card table-card"><div className="table-head"><h2 className="section-title" style={{margin:0}}>Lançamentos</h2><span className="muted">{data.length} registro(s)</span></div><div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Vaga</th><th>Valor</th><th>Comissão</th><th>Vencimento</th><th>Nota</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.map((r:any)=><tr key={r.id}><td>{r.vagas?.empresas?.nome||'—'}</td><td><b>{r.vagas?.cargo||'—'}</b></td><td>{Number(r.valor).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td>{Number(r.valor_comissao||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td>{r.data_vencimento?new Date(r.data_vencimento+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</td><td>{r.nota_emitida?(r.numero_nota||'Emitida'):'Não emitida'}</td><td><span className={'badge '+badgeClass(r.status)}>{label(r.status)}</span></td><td><div className="actions-cell">
      <form action={baixar}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="pago" value={String(!r.pago)}/><button className="small-button">{r.pago?'Reabrir':'Marcar pago'}</button></form>
      <EditModal title={'Editar lançamento — '+(r.vagas?.cargo||'Financeiro')} action={editar}><input type="hidden" name="id" value={r.id}/><div className="field-group"><label>Valor</label><input name="valor" type="number" step="0.01" min="0" defaultValue={r.valor}/></div><div className="field-group"><label>Comissão %</label><input name="percentual" type="number" step="0.01" min="0" max="100" defaultValue={r.percentual}/></div><div className="field-group"><label>Status</label><select name="status" defaultValue={r.status}>{['pendente','parcial','pago','vencido','cancelado'].map(x=><option value={x} key={x}>{label(x)}</option>)}</select></div><div className="field-group"><label>Vencimento</label><input name="data_vencimento" type="date" defaultValue={r.data_vencimento||''}/></div><div className="field-group"><label>Data do pagamento</label><input name="data_pagamento" type="date" defaultValue={r.data_pagamento||''}/></div><div className="field-group"><label>Nº da nota</label><input name="numero_nota" defaultValue={r.numero_nota||''}/></div><label className="check-field"><input type="checkbox" name="pago" defaultChecked={r.pago}/> Pago</label><label className="check-field"><input type="checkbox" name="nota_emitida" defaultChecked={r.nota_emitida}/> Nota emitida</label><div className="field-group wide"><label>Observações</label><textarea name="observacoes" defaultValue={r.observacoes||''}/></div></EditModal>
      <DeleteButton id={r.id} action={excluir} label="lançamento"/>
    </div></td></tr>)}</tbody></table>{!data.length&&<div className="empty">Nenhum lançamento financeiro.</div>}</div></div>
  </section>
}
