import Link from 'next/link';
import {revalidatePath} from 'next/cache';
import {BriefcaseBusiness,CheckCircle2,Clock3,Download,PauseCircle,Plus,Search,SlidersHorizontal} from 'lucide-react';
import {createClient} from '@/lib/supabase/server';
import {EmptyRow,KpiCard,PageHeader} from '@/components/ModuleUI';
import { ActionModal } from "@/components/ActionModal";

type Params={q?:string;empresa?:string;etapa?:string;status?:string;ordem?:string;pagina?:string};
type Row=Record<string,any>;
const statusLabel:Record<string,string>={rascunho:'Rascunho',em_andamento:'Ativa',congelada:'Pausada',completada:'Encerrada',cancelada:'Encerrada'};
const stageClass:Record<string,string>={Candidatos:'stage-blue',Triagem:'stage-yellow',Entrevistas:'stage-blue',Finalistas:'stage-green','Em análise':'stage-neutral'};
function etapa(row:Row){const stages=(row.candidaturas||[]).map((x:Row)=>x.status);if(stages.some((x:string)=>['contratado','aprovado'].includes(x)))return'Finalistas';if(stages.includes('entrevista'))return'Entrevistas';if(stages.includes('triagem'))return'Triagem';if(stages.includes('novo'))return'Candidatos';return'Em análise'}
function prazo(row:Row){const date=new Date(row.prazo_fechamento||row.data_requisicao||row.created_at);const n=row.prazo_fechamento?Math.ceil((date.getTime()-Date.now())/86400000):Math.max(0,Math.ceil((Date.now()-date.getTime())/86400000));return`${Math.abs(n)} ${Math.abs(n)===1?'dia':'dias'}`}

export default async function Page({searchParams}:{searchParams:Promise<Params>}){
 async function criar(f:FormData){'use server';const s=await createClient();const {error}=await s.from('vagas').insert({empresa_id:String(f.get('empresa_id')),requisicao:String(f.get('requisicao')||'')||null,cargo:String(f.get('cargo')),area:String(f.get('area')||'')||null,local:String(f.get('local')||'')||null,estado:String(f.get('estado')||'')||null,quantidade:Number(f.get('quantidade')||1),tipo_contrato:String(f.get('tipo_contrato')||'')||null,gestor:String(f.get('gestor')||'')||null,salario:f.get('salario')?Number(f.get('salario')):null,confidencial:f.get('confidencial')==='on',pcd:f.get('pcd')==='on',substituicao:String(f.get('substituicao')||'')||null,solicitante:String(f.get('solicitante')||'')||null,email_solicitante:String(f.get('email_solicitante')||'')||null,telefone_solicitante:String(f.get('telefone_solicitante')||'')||null,modelo_trabalho:String(f.get('modelo_trabalho')||'')||null,horario_trabalho:String(f.get('horario_trabalho')||'')||null,responsabilidades:String(f.get('responsabilidades')||'')||null,requisitos:String(f.get('requisitos')||'')||null,empresas_restritas:String(f.get('empresas_restritas')||'')||null});if(error)throw new Error(error.message);revalidatePath('/vagas');revalidatePath('/dashboard')}
 async function atualizar(f:FormData){'use server';const s=await createClient();const {error}=await s.from('vagas').update({cargo:String(f.get('cargo')),empresa_id:String(f.get('empresa_id')),local:String(f.get('local')||'')||null,estado:String(f.get('estado')||'')||null,status:String(f.get('status')),prazo_fechamento:String(f.get('prazo_fechamento')||'')||null}).eq('id',String(f.get('id')));if(error)throw new Error(error.message);revalidatePath('/vagas');revalidatePath('/dashboard');revalidatePath('/candidaturas')}
 const params=await searchParams,s=await createClient();
 const [{data:allRows},{data:empresas}]=await Promise.all([s.from('vagas').select('*,empresas(nome),candidaturas(id,status)').order('created_at',{ascending:false}),s.from('empresas').select('id,nome').eq('ativo',true).order('nome')]);
 const raw=(allRows||[]) as Row[],query=(params.q||'').trim().toLocaleLowerCase('pt-BR');
 let filtered=raw.filter(r=>{const text=[r.requisicao,r.cargo,r.empresas?.nome,r.local,r.estado].filter(Boolean).join(' ').toLocaleLowerCase('pt-BR');return(!query||text.includes(query))&&(!params.empresa||r.empresa_id===params.empresa)&&(!params.etapa||etapa(r)===params.etapa)&&(!params.status||r.status===params.status)});
 if(params.ordem==='antigas')filtered=[...filtered].reverse();if(params.ordem==='cargo')filtered=[...filtered].sort((a,b)=>String(a.cargo).localeCompare(String(b.cargo),'pt-BR'));
 const size=10,pages=Math.max(1,Math.ceil(filtered.length/size)),page=Math.min(pages,Math.max(1,Number(params.pagina)||1)),rows=filtered.slice((page-1)*size,page*size);
 const active=raw.filter(r=>r.status==='em_andamento').length,paused=raw.filter(r=>r.status==='congelada').length,closed=raw.filter(r=>['completada','cancelada'].includes(r.status)).length;
 const href=(value:number)=>{const p=new URLSearchParams(Object.entries(params).filter(([,v])=>v).map(([k,v])=>[k,String(v)]));p.set('pagina',String(value));return`/vagas?${p}`};
 return <section className="module-page vacancies-page">
  <PageHeader title="Vagas" description="Gerencie as vagas de emprego e acompanhe todo o processo seletivo." action={<><details className="action-popover vacancy-create"><summary><Plus size={17}/> Nova vaga</summary><VacancyForm empresas={empresas||[]} action={criar}/></details><a className="outline-button export-button" href="/api/vagas?format=csv" download><Download size={15}/> Exportar</a></>}/>
  <div className="module-kpis four"><KpiCard Icon={BriefcaseBusiness} value={active} label="Vagas ativas" note="↑ acompanhamento atualizado"/><KpiCard Icon={Clock3} value={active} label="Em andamento" note="↑ processos em seleção"/><KpiCard Icon={PauseCircle} value={paused} label="Pausadas" note="Sem movimentação ativa" tone="yellow"/><KpiCard Icon={CheckCircle2} value={closed} label="Encerradas" note="↑ histórico consolidado" tone="green"/></div>
  <div className="module-panel vacancies-panel">
   <form className="filterbar vacancies-filters" method="get"><label className="searchbox"><Search size={15}/><input name="q" defaultValue={params.q} placeholder="Buscar por cargo, empresa ou requisição..."/></label><select name="empresa" defaultValue={params.empresa||''}><option value="">Todas as empresas</option>{(empresas||[]).map((e:Row)=><option key={e.id} value={e.id}>{e.nome}</option>)}</select><select name="etapa" defaultValue={params.etapa||''}><option value="">Todas as etapas</option>{['Candidatos','Triagem','Entrevistas','Finalistas','Em análise'].map(x=><option key={x}>{x}</option>)}</select><select name="status" defaultValue={params.status||''}><option value="">Todos os status</option><option value="em_andamento">Ativa</option><option value="congelada">Pausada</option><option value="completada">Encerrada</option><option value="rascunho">Rascunho</option></select><select name="ordem" defaultValue={params.ordem||'recentes'}><option value="recentes">Mais recentes</option><option value="antigas">Mais antigas</option><option value="cargo">Cargo A–Z</option></select><button className="filter-submit" title="Aplicar filtros"><SlidersHorizontal size={15}/></button></form>
   <div className="table-wrap"><table className="module-table vacancies-table"><thead><tr><th>Requisição ↕</th><th>Cargo ↕</th><th>Empresa ↕</th><th>Local</th><th>Etapa ↕</th><th>Prazo ↕</th><th>Status ↕</th><th>Ações</th></tr></thead><tbody>{rows.map(r=>{const stage=etapa(r);return <tr key={r.id}><td><b>{r.requisicao||'—'}</b></td><td>{r.cargo}</td><td>{r.empresas?.nome||'—'}</td><td>{[r.local,r.estado].filter(Boolean).join('/')||'—'}</td><td><span className={`vacancy-stage ${stageClass[stage]}`}>{stage}</span></td><td>{prazo(r)}</td><td><span className={`status-chip ${r.status==='em_andamento'?'success':r.status==='congelada'?'warning':'neutral'}`}>{statusLabel[r.status]||r.status}</span></td><td><div className="row-actions"><ActionModal kind="view" title={r.cargo}><div><b>{r.cargo}</b><small>Requisição {r.requisicao||'não informada'}</small><p><strong>Empresa:</strong> {r.empresas?.nome||'—'}</p><p><strong>Local:</strong> {[r.local,r.estado].filter(Boolean).join('/')||'—'}</p><p><strong>Candidatos:</strong> {r.candidaturas?.length||0}</p><p><strong>Requisitos:</strong> {r.requisitos||'Não informados'}</p></div></ActionModal><ActionModal kind="edit" title={r.cargo}><form action={atualizar}><input type="hidden" name="id" value={r.id}/><label>Cargo<input name="cargo" defaultValue={r.cargo} required/></label><label>Empresa<select name="empresa_id" defaultValue={r.empresa_id}>{(empresas||[]).map((e:Row)=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></label><label>Local<input name="local" defaultValue={r.local||''}/></label><label>UF<input name="estado" maxLength={2} defaultValue={r.estado||''}/></label><label>Prazo<input name="prazo_fechamento" type="date" defaultValue={r.prazo_fechamento||''}/></label><label>Status<select name="status" defaultValue={r.status}><option value="rascunho">Rascunho</option><option value="em_andamento">Ativa</option><option value="congelada">Pausada</option><option value="completada">Encerrada</option><option value="cancelada">Cancelada</option></select></label><button className="primary-button">Salvar alterações</button></form></ActionModal></div></td></tr>})}{!rows.length&&<EmptyRow colSpan={8} label="Nenhuma vaga encontrada com estes filtros."/>}</tbody></table></div>
   <div className="pagination"><span>Mostrando {filtered.length?(page-1)*size+1:0} a {Math.min(page*size,filtered.length)} de {filtered.length} vagas</span><nav>{page>1&&<Link href={href(page-1)}>‹</Link>}{Array.from({length:pages},(_,i)=><Link key={i} className={page===i+1?'active':''} href={href(i+1)}>{i+1}</Link>)}{page<pages&&<Link href={href(page+1)}>›</Link>}</nav></div>
  </div>
 </section>
}

function VacancyForm({empresas,action}:{empresas:Row[];action:(f:FormData)=>void}){return <form className="popover-form vacancy-form" action={action}><div className="field-group"><label>Empresa</label><select name="empresa_id" required defaultValue=""><option value="" disabled>Selecione</option>{empresas.map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></div><div className="field-group"><label>Requisição</label><input name="requisicao"/></div><div className="field-group"><label>Cargo</label><input name="cargo" required/></div><div className="field-group"><label>Área</label><input name="area"/></div><div className="field-group"><label>Quantidade</label><input name="quantidade" type="number" min="1" defaultValue="1"/></div><div className="field-group"><label>Contrato</label><select name="tipo_contrato"><option>CLT</option><option>ESTAGIO</option><option>PJ</option><option>TEMPORÁRIO</option></select></div><div className="field-group"><label>Gestor</label><input name="gestor"/></div><div className="field-group"><label>Solicitante</label><input name="solicitante"/></div><div className="field-group"><label>E-mail solicitante</label><input name="email_solicitante" type="email"/></div><div className="field-group"><label>WhatsApp</label><input name="telefone_solicitante"/></div><div className="field-group"><label>Local</label><input name="local"/></div><div className="field-group"><label>UF</label><input name="estado" maxLength={2}/></div><div className="field-group"><label>Salário</label><input name="salario" type="number" step=".01"/></div><div className="field-group"><label>Modelo</label><select name="modelo_trabalho"><option value="">Selecione</option><option>Presencial</option><option>Híbrido</option><option>Remoto</option></select></div><div className="field-group"><label>Horário</label><input name="horario_trabalho"/></div><div className="field-group"><label>Substituição</label><select name="substituicao"><option>NÃO</option><option>VOLUNTÁRIO</option><option>INVOLUNTÁRIO</option></select></div><label className="check-field"><input type="checkbox" name="confidencial"/> Vaga confidencial</label><label className="check-field"><input type="checkbox" name="pcd"/> Vaga PCD</label><div className="field-group wide"><label>Responsabilidades e atribuições</label><textarea name="responsabilidades"/></div><div className="field-group wide"><label>Requisitos da vaga</label><textarea name="requisitos"/></div><div className="field-group wide"><label>Empresas que não devem ser abordadas</label><textarea name="empresas_restritas"/></div><button className="primary-button">Cadastrar vaga</button></form>}
